SELECT PROJECT.*, EMP_NAME
	    FROM PROJECT, PROJECT_WITH, EMP
		WHERE PROJECT.PROJECT_INDEX = PROJECT_WITH.PROJECT_INDEXRA
	        AND PROJECT_WITH.PROJECT_WITH_LEADER = EMP.EMP_INDEX
	        AND PROJECT_WITH_EMP_INDEX = 8;
            
-- ¿ø·¡ SQL
SELECT PROJECT.*, EMP_NAME
	    FROM PROJECT, PROJECT_WITH, EMP
		WHERE PROJECT.PROJECT_INDEX = PROJECT_WITH.PROJECT_INDEX
	        AND PROJECT_WITH.PROJECT_WITH_LEADER = EMP.EMP_INDEX
	        AND TO_CHAR(SYSDATE, 'YYYY-MM-DD') 
	            BETWEEN PROJECT_START AND PROJECT_END
	        AND PROJECT_WITH_EMP_INDEX = 8;
            
